---
# Check image size

- name: get image size with docker
  shell: docker image ls {{ image_fullname }} |  tail -n1 | tr -s ' ' | rev | cut -d ' ' -f2 | rev
  become: true
  register: image_size
  when: ansible_distribution_major_version == '7'

- set_fact: my_image_size="{{ image_size }}"
  when: image_size.changed

- name: get image size with podman
  shell: podman inspect {{ image_fullname }} --format \{\{.Size\}\}
  become: true
  register: image_size
  when: ansible_distribution_major_version == '8'

- set_fact: my_image_size="{{ image_size }}"
  when: image_size.changed

- name: debug
  debug:
    var: my_image_size.stdout

- name: check container size
  fail:
    msg: "The image has wrong size!"
  when: my_image_size.stdout|int > size_max or my_image_size.stdout|int < size_min
