---
# Check rpms in container are signed correctly.

- name: check rpm signatures with podman
  shell: |
    for r in `podman run --rm {{ image_fullname }} rpm -qa | grep -v gpg-pubkey`
    do
      a=`podman run --rm {{ image_fullname }} rpm -qi $r | grep 199e2f91fd431d51`
      if [ -z "$a" ]
      then
        echo "$r has wrong signature"
      fi
    done
  become: true
  register: sig_result
  failed_when: "'wrong' in sig_result.stdout"
