---
# This playbook is to test rhel-tools container image

- hosts: all
  vars:
    image_name: /rhel7/rhel-tools
    # normal size is 352, and min is like 0.9 * normal
    size_min: 317
    # normal size is 352, and max is like 1.1 * normal
    size_max: 387

  roles:
  - setup
  - pull
  - scan
  - check_signature
  - check_size
