---
# This playbook is to test rhel-tools container image
# For now, only RHEL7 has this image.

- hosts: all
  vars:
    # normal size is 352, and min is like 0.9 * normal
    size_min: 317
    # normal size is 352, and max is like 1.1 * normal
    size_max: 387

  roles:
  - setup
  - pull
    #- scan
  - check_signature
  - check_label_version
    # - check_size

  post_tasks:
    - name: check the tools are included in this image.
      shell: podman run --rm  {{ image_fullname }} /bin/bash -c "command -v useradd && command -v blktrace"
      become: true
