---
# This playbook is to test rsyslog container image

- hosts: all
  vars_files:
    - vars/rsyslog_vars.yml

  roles:
  - setup
  - pull
  - scan
  - check_signature
  - check_size
  - install_and_run
