---
# This playbook is to test rsyslog container image

- hosts: all

  pre_tasks:
  - include_vars: rsyslog_rhel7_vars.yml
    when: ansible_distribution_major_version == '7'

  - include_vars: rsyslog_rhel8_vars.yml
    when: ansible_distribution_major_version == '8'

  roles:
  - setup
  - pull
  # only rhel7 container can be scanned now.
  - scan
  - check_signature
  - check_size
  - install_and_run
