---
# This playbook is to test rsyslog container image

- hosts: all

  pre_tasks:
  - name: print distribution and architecture
    debug:
      msg: "{{ ansible_distribution_major_version }} has {{ ansible_architecture }}"

  - name: check if rsyslog is running
    shell: systemctl is-active --quiet rsyslog
    become: true
    register: rst
    ignore_errors: yes

  - name: stop if it's been started
    shell: systemctl stop rsyslog
    become: true
    when: rst.rc == 0

  - include_vars: rsyslog_rhel7_vars.yml
    when: ansible_distribution_major_version == '7' and ansible_architecture == 'x86_64'

  - include_vars: rsyslog_rhel7_ppc_vars.yml
    when: ansible_distribution_major_version == '7' and ansible_architecture == 'ppc64le'

  - include_vars: rsyslog_rhel7_s390x_vars.yml
    when: ansible_distribution_major_version == '7' and ansible_architecture == 's390x'

  - include_vars: rsyslog_rhel8_vars.yml
    when: ansible_distribution_major_version == '8' and ansible_architecture == 'x86_64'

  - include_vars: rsyslog_rhel8_ppc_vars.yml
    when: ansible_distribution_major_version == '8' and ansible_architecture == 'ppc64le'

  - include_vars: rsyslog_rhel8_s390x_vars.yml
    when: ansible_distribution_major_version == '8' and ansible_architecture == 's390x'

  roles:
  - setup
  - pull
  # only rhel7 container can be scanned now.
  #- scan
  - check_signature
  - check_label_version
  - check_size
  - install_and_run

  post_tasks:
  - name: pause for 1 min to wait for container setup
    pause:
      minutes: 1

   # We're not going to cover all the features, since the rpm has been tested already.
  - name: check rsyslog within the container works fine
    shell: logger "woohaa" && sleep 30 && grep woohaa /var/log/messages
    become: true
