
# This playbook is to test sadc container image.
# Only rhel7 has this container images.

- hosts: all

  pre_tasks:
  - name: print distribution and architecture
    debug:
      msg: "{{ ansible_distribution_major_version }} has {{ ansible_architecture }}"

  - include_vars: sadc_rhel7_vars.yml
    when: ansible_architecture == 'x86_64'

  - include_vars: sadc_rhel7_ppc_vars.yml
    when: ansible_architecture == 'ppc64le'

  - include_vars: sadc_rhel7_s390x_vars.yml
    when: ansible_architecture == 's390x'

  roles:
  - setup
  - pull
  - check_signature
  - check_label_version
    #- check_size
  - install_and_run
    #  - scan

  post_tasks:
  # We're not going to cover all the features, since the rpm has been tested.
  - name: run sa1 command within the container with docker
    shell: podman exec {{ container_name }} /usr/lib64/sa/sa1 1 1
    become: true

  - set_fact:
      dir_name: /var/log/sa/sa{{ ansible_date_time.day }}

  - debug: msg="working dir is {{ dir_name }}"

  - name: check the working directory is created
    stat:
      path: "{{ dir_name }}"
