---
# This playbook is to test support-tools container image.
# This image just has x64_64 version for rhel7, but has x64_64, s390x and ppc64le for rhel8.

- hosts: all

  pre_tasks:
  - include_vars: support_tools_rhel7_vars.yml
    when: ansible_distribution_major_version == '7' and ansible_architecture == 'x86_64'
  - include_vars: support_tools_rhel7_ppc_vars.yml
    when: ansible_distribution_major_version == '7' and ansible_architecture == 'ppc64le'
  - include_vars: support_tools_rhel7_s390x_vars.yml
    when: ansible_distribution_major_version == '7' and ansible_architecture == 's390x'
  - include_vars: support_tools_rhel8_vars.yml
    when: ansible_distribution_major_version == '8' and ansible_architecture == 'x86_64'
  - include_vars: support_tools_rhel8_ppc_vars.yml
    when: ansible_distribution_major_version == '8' and ansible_architecture == 'ppc64le'
  - include_vars: support_tools_rhel8_s390x_vars.yml
    when: ansible_distribution_major_version == '8' and ansible_architecture == 's390x'

  roles:
  - setup
  - pull
    #  - scan
  - check_signature
  - check_label_version
  - check_size

  post_tasks:
  - set_fact:
      vir_time: "{{ ansible_date_time.epoch }}"

  - debug: msg="{{ vir_time }}"

    # - name: run sosreport within the container with podman
    #   expect:
    #     echo: yes
    #     command: "podman container runlabel run {{ image_fullname }}"
    #     timeout: null
    #     responses:
    #       (.*)bash(.*)#: ["sosreport", "exit"]
    #       (.*)Press ENTER(.*): ""
    #       (.*)enter the case id(.*): "cvp-{{ vir_time }}"
    #   become: true
    #   when: ansible_distribution_major_version == '8'

    # - name: check the report has been stored in host
    #   shell: ls /var/tmp | grep "sosreport.*{{ vir_time }}"

    # - name: remove the reports to release storage
    #   shell: rm -f /var/tmp/sosreport*
    #   become: true

  - name: check tcpdump is installed with podman
    shell: podman run --rm {{ image_fullname }} rpm -q tcpdump
    become: true

  - name: check strace is installed
    shell: podman run --rm {{ image_fullname }} rpm -q strace
    become: true
    when: ansible_distribution_major_version == '7'

# Only rhel8 support-tools has strace
  - name: check mtr strace and telnet is installed
    shell: podman run --rm {{ image_fullname }} rpm -q strace mtr telnet
    become: true
    when: ansible_distribution_major_version == '8'
