---
# This playbook is to test ubi9 container image
# Because it's very like ubi8 container testing, use ubi8 vars and files here.

- hosts: all

  pre_tasks:
  - include_vars: ubi8_vars.yml

  roles:
  - setup
  - pull
  - check_signature
  - check_label_version
    #  - check_size

  post_tasks:
  # Refer to https://bugzilla.redhat.com/show_bug.cgi?id=1549765
  - name: set boolean container_manage_cgroup to 1
    shell: setsebool -P container_manage_cgroup 1
    become: true

  - name: check eula correctness with podman
    shell: podman inspect {{ image_fullname }} | grep {{ eula_link }}
    become: true

  - name: check repo file with podman
    shell: podman run --rm {{ image_fullname }} ls /etc/yum.repos.d | grep "ubi\.repo"
    become: true

  - name: check pem file with podman for arch x86_64
    shell: podman run --rm {{ image_fullname }} ls /etc/pki/product-default | grep "479\.pem"
    become: true
    when: ansible_architecture == 'x86_64'
  
  - name: check pem file with podman for arch ppc64le
    shell: podman run --rm {{ image_fullname }} ls /etc/pki/product-default | grep "279\.pem"
    become: true
    when: ansible_architecture == 'ppc64le'
  
  - name: check pem file with podman for arch s390x
    shell: podman run --rm {{ image_fullname }} ls /etc/pki/product-default | grep "72\.pem"
    become: true
    when: ansible_architecture == 's390x'

  - name: check pem file with podman for arch aarch64
    shell: podman run --rm {{ image_fullname }} ls /etc/pki/product-default | grep "419\.pem"
    become: true
    when: ansible_architecture == 'aarch64'

  - name: create dockerfile with rhel content
    template:
      src: Dockerfile-ubi8-rhel.j2
      dest: /tmp/Dockerfile-ubi9-rhel
    become: true

  - name: remove existing rhel content image
    shell: podman rmi -f ubi9-build-rhel
    ignore_errors: yes
    become: true

  - name: remove existing rhel content container
    shell: podman rm -f ubi9-container-rhel
    ignore_errors: yes
    become: true

  - name: build the rhel content image
    shell: podman build -f /tmp/Dockerfile-ubi9-rhel -t ubi9-build-rhel /tmp/
    become: true

  - name: run the rhel content image
    shell: podman run --name ubi9-container-rhel ubi9-build-rhel
    register: result_out
    failed_when: "'traceroute to www.amazon.com' not in result_out.stdout"
    become: true
