---
# This playbook is to check container installation and mounted directories

- name: install
  shell: podman container runlabel install {{ image_fullname }}
  become: true

- name: check install files
  stat:
    path: "{{ item }}"
  register: r
  failed_when: r.stat.exists == False
  with_items: "{{ install_files }}"

- name: check /var/log/sa for sadc
  stat:
    path: /var/log/sa
  ignore_errors: yes
  register: check_sa

- name: create dir /var/log/sa
  file:
    path: /var/log/sa
    state: directory
  when: check_sa.stat.exists == False

- name: run
  shell: podman container runlabel run {{ image_fullname }}
  become: true

- name: check mounts
  # About the {% raw %} please see https://github.com/ansible/ansible/issues/21304
  shell: podman inspect --format '{% raw %}{{ range .Mounts }}{{ .Source }} {{ end }}{% endraw %}' {{ container_name }} | tr " " "\n" | sed '/^\s*$/d' | sort | tr "\n" " "
  become: true
  register: mounts_result
  failed_when: "mounts_result.stdout != mounts"
