---
# This playbook is to check container installation and mounted directories

  # This is supposed to be done by command podman container runlabel, but --always flag is still not implemented yet.
- name: install
  shell: podman run --rm --privileged -v /:/host -e HOST=/host -e IMAGE={{ image_fullname }} -e NAME=rsyslog {{ image_fullname }} /bin/install.sh
  become: true
  when: container_name == "rsyslog"

- name: install
  shell: podman run --rm --privileged -v /:/host -e HOST=/host -e IMAGE={{ image_fullname }} -e NAME={{ container_name }} {{ image_fullname }} /usr/local/bin/sysstat-install.sh
  become: true
  when: container_name == "sadc"

- name: check install files
  stat:
    path: "{{ item }}"
  register: r
  failed_when: r.stat.exists == False
  with_items: "{{ install_files }}"

  # This is supposed to be done by command podman container runlabel, but --always flag is still not implemented yet.
- name: run
  shell: podman run -d --privileged --name rsyslog --net=host --pid=host -v /etc/pki/rsyslog:/etc/pki/rsyslog -v /etc/rsyslog.conf:/etc/rsyslog.conf -v /etc/sysconfig/rsyslog:/etc/sysconfig/rsyslog -v /etc/rsyslog.d:/etc/rsyslog.d -v /var/log:/var/log -v /var/lib/rsyslog:/var/lib/rsyslog -v /run:/run -v /etc/machine-id:/etc/machine-id -v /etc/localtime:/etc/localtime -e IMAGE={{ image_fullname }} -e NAME=rsyslog {{ image_fullname }} /bin/rsyslog.sh
  become: true
  when: container_name == "rsyslog"

- name: run
  shell: podman run -d --privileged --name sadc -v /etc/sysconfig/sysstat:/etc/sysconfig/sysstat -v /etc/sysconfig/sysstat.ioconf:/etc/sysconfig/sysstat.ioconf -v /var/log/sa:/var/log/sa -v /:/host -e HOST=/host -e IMAGE={{ image_fullname }} -e NAME=rhel7-sadc --net=host {{ image_fullname }} /usr/local/bin/sysstat.sh
  become: true
  when: container_name == "sadc"

- name: check mounts
  # About the {% raw %} please see https://github.com/ansible/ansible/issues/21304
  shell: podman inspect --format '{% raw %}{{ range .Mounts }}{{ .Source }} {{ end }}{% endraw %}' {{ container_name }} | tr " " "\n" | sed '/^\s*$/d' | sort | tr "\n" " "
  become: true
  register: mounts_result
  failed_when: "mounts_result.stdout != mounts"
