FROM {{ image_fullname }}
MAINTAINER  Atomic QE "atomic-qe@redhat.com"

RUN microdnf install -y --enablerepo=ubi-7-for-system-z-rpms wget && microdnf clean all

CMD ["/usr/bin/wget", "access.redhat.com"]
