FROM {{ image_fullname }}
MAINTAINER Edward Shen "weshen@redhat.com"

RUN yum -y install --disablerepo=* --enablerepo=rhel-6-server-rpms httpd
RUN echo "RHEL6 base container CI test" > /var/www/html/index.html
RUN chkconfig httpd on

EXPOSE 80