FROM {{ image_fullname }}
MAINTAINER  Atomic QE "atomic-qe@redhat.com"

RUN microdnf install -y --enablerepo=ubi-9-appstream-rpms wget && microdnf clean all

CMD ["/usr/bin/wget", "access.redhat.com"]
