FROM brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888{{ image_version }}
MAINTAINER Edward Shen "weshen@redhat.com"

RUN yum install -y httpd && yum clean all && systemctl enable httpd
RUN echo "hello from Edward" > /var/www/html/index.html

EXPOSE 80