FROM {{ image_fullname }}
MAINTAINER  Atomic QE "atomic-qe@redhat.com"

RUN dnf install -y --disablerepo=* --enablerepo=ubi-8-appstream wget && dnf clean all

CMD ["/usr/bin/wget", "access.redhat.com", "2>&1"]
