FROM {{ image_fullname }}
MAINTAINER Atomic QE "atomic-qe@redhat.com"

RUN microdnf install -y httpd && microdnf clean all && systemctl enable httpd
RUN echo "RHEL atomic httpd images" > /var/www/html/index.html

EXPOSE 80