---
## This playbook makes the environment ready to pull and test the container images.

# Add insecure registry if its not added yet, and restart docker service
  - name: check insecure registry is added
    shell: grep -Pz '\[registries\.insecure\]\nregistries = \[\]' /etc/containers/registries.conf
    ignore_errors: yes
    register: check_insecure

  - name: add insecure registry
    lineinfile:
      path: /etc/containers/registries.conf
      regexp: '^registries = \[\]'
      # dont know why insertafter: '^\[registries\.insecure\]$' does NOT work here
      insertbefore: '^\[registries\.block\]$'
      firstmatch: yes
      line: "registries = ['brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888', 'registry-proxy.engineering.redhat.com']"
    when: check_insecure.stdout != ""
    become: true

  - name: restart docker service
    service:
      name: docker
      state: restarted
    become: true
    when: ansible_distribution_major_version == '7'

# We're not going to remove all the images, and not going to remove the containers as a Tear-Down.
# Because sometimes we just want to keep the "scene of crime".
  - name: delete all containers with atomic
    expect:
      echo: yes
      command: atomic containers delete -af
      timeout: null
      responses:
        (.*)Confirm(.*): "y"
    become: true
    ignore_errors: yes
    when: ansible_distribution_major_version == '7'

  - name: delete all containers with podman
    shell: podman rm -af
    become: true
    ignore_errors: yes
    when: ansible_distribution_major_version == '7' or ansible_distribution_major_version == '8'